/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chess;

import javax.swing.JFrame;

/**
 *
 * @author 154003771
 */
public class startScreen extends javax.swing.JFrame {
    static PlayerVsPlayer playerScreen;
    /**
     * Creates new form startScreen
     */
    public startScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jPanel1 = new javax.swing.JPanel();
        playerVPlayer = new javax.swing.JButton();
        playerVPlayer1 = new javax.swing.JButton();
        playerVPlayer2 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(239, 228, 176));
        jPanel1.setForeground(new java.awt.Color(239, 228, 176));

        playerVPlayer.setBackground(new java.awt.Color(0, 0, 0));
        playerVPlayer.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        playerVPlayer.setForeground(new java.awt.Color(255, 255, 255));
        playerVPlayer.setText("Player Vs Player");
        playerVPlayer.setBorder(null);
        playerVPlayer.setBorderPainted(false);
        playerVPlayer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playerVPlayer.setFocusPainted(false);
        playerVPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerVPlayerActionPerformed(evt);
            }
        });

        playerVPlayer1.setBackground(new java.awt.Color(0, 0, 0));
        playerVPlayer1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        playerVPlayer1.setForeground(new java.awt.Color(255, 255, 255));
        playerVPlayer1.setText("Player Vs AI");
        playerVPlayer1.setBorder(null);
        playerVPlayer1.setBorderPainted(false);
        playerVPlayer1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playerVPlayer1.setFocusPainted(false);
        playerVPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerVPlayer1ActionPerformed(evt);
            }
        });

        playerVPlayer2.setBackground(new java.awt.Color(0, 0, 0));
        playerVPlayer2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        playerVPlayer2.setForeground(new java.awt.Color(255, 255, 255));
        playerVPlayer2.setText("Blitz Mode");
        playerVPlayer2.setBorder(null);
        playerVPlayer2.setBorderPainted(false);
        playerVPlayer2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playerVPlayer2.setFocusPainted(false);
        playerVPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerVPlayer2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(94, 481, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerVPlayer2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerVPlayer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerVPlayer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(playerVPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(playerVPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(playerVPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playerVPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerVPlayerActionPerformed
        // TODO add your handling code here:
        playerScreen = new PlayerVsPlayer();
        playerScreen.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        playerScreen.setVisible(true);
        dispose();
    }//GEN-LAST:event_playerVPlayerActionPerformed

    private void playerVPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerVPlayer1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_playerVPlayer1ActionPerformed

    private void playerVPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerVPlayer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerVPlayer2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new startScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private javax.swing.JButton playerVPlayer;
    private javax.swing.JButton playerVPlayer1;
    private javax.swing.JButton playerVPlayer2;
    // End of variables declaration//GEN-END:variables
}
